apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.role .Values.machineset.zone }}
  namespace: openshift-machine-api
  annotations:
    meta.helm.sh/release-name: development
    meta.helm.sh/release-namespace: openshift-machine-api
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  minReplicas: 0
  maxReplicas: 12
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ printf "%v-%v-%v" .Values.machineset.infrastructure_id .Values.machineset.role .Values.machineset.zone }}
