apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: {{ .Values.machineset.role }}
  annotations:
    meta.helm.sh/release-name: development
    meta.helm.sh/release-namespace: {{ .Values.default.namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  priorityClassName: {{ .Values.priority_class_name.low }}
  watermarkPercentage: 20
  nodeSelector:
    machine-set-group: proactive-autoscaler-operator
