apiVersion: redhatcop.redhat.io/v1alpha1
kind: NodeScalingWatermark
metadata:
  name: {{ .Values.machineset.role }}
spec:
  priorityClassName: proactive-node-autoscaling-pods
  watermarkPercentage: 20
  nodeSelector:
    {{ printf "node-role.kubernetes.io/%v: ''" .Values.machineset.role }}
