apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal-workload
  annotations:
    meta.helm.sh/release-name: development
  labels:
    app.kubernetes.io/managed-by: Helm
value: 1000
globalDefault: true
description: "This priority class is the cluster default and should be used for normal workloads."
