apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: proactive-node-scaling-operator
spec:
  channel: alpha
  installPlanApproval: {{ .Values.installPlanApproval }}
  name: proactive-node-scaling-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
